# The packages for each backend in group files can come in two formats, short-form
# and long-form:
#
# short-form syntax is simply a string of the name of the package.
#
# long-form syntax is a table which contains several fields which can
# optionally be set to specify install options on a per-package basis.
# The "package" field in the table specifies the name of the package.
#
# For example, the following two packages are equivalent:
# arch = [
#  "metapac",
#  { package = "metapac" }
# ]

arch = [
  "1password",
  "1password-cli",
  "bat",
  "diff-so-fancy",
  "git",
  "git-lfs",
  "sops",
]
brew = [
  "1password",
  "1password-cli",
  "alfred",
  "bat",
  "coreutils",
  "diff-so-fancy",
  "findutils",
  "git",
  "git-lfs",
  "sops",
]
cargo = ["cargo-binstall", "cargo-update", "metapac"]
flatpak = []
mise = []
npm = []
