k9s:
  liveViewAutoRefresh: true #
  refreshRate: 1 #
  gpuVendors: {}
  screenDumpDir: /home/svenh/.local/state/k9s/screen-dumps
  apiServerTimeout: 2m0s
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  portForwardAddress: localhost
  ui:
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    splashless: true
    reactive: true
    noIcons: false
    invert: false
    defaultsToFullScreen: false
    useFullGVRTitle: false
    skin: "transparent"
  skipLatestRevCheck: true
  disablePodCounting: false
  shellPod:
    image: busybox:1.37.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    disableAutoscroll: false
    columnLock: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 75
    memory:
      critical: 90
      warn: 75
  defaultView: "pod"
